services:
  code:
    build: .
    container_name: python-vscode-pytest
    environment:
      - PASSWORD=miclave123  # Puedes cambiarla
    ports:
      - "8444:8080"
    volumes:
      - ./data:/home/coder/project     # Aquí irá tu proyecto y cambios
      - ./vscode:/home/coder/.local/share/code-server  # Persistencia de config/extensions
    restart: unless-stopped